INSERT INTO ocean_shipments (
  consignee_name, shipper_name, shipper_country, consignee_country, 
  consignee_city, consignee_state, consignee_zip, goods_description,
  weight_kg, port_of_lading, port_of_unlading, transport_method,
  vessel_name, arrival_date, bol_number, raw_xml_filename
) VALUES (
  'Utilitymate Mfg.',
  'Asen Prefab House Co., Ltd.',
  'China',
  'Port of Portland, Portland, Oregon',
  'Grants Pass',
  'Oregon',
  '97526',
  'PREFABRICATED HOUSE (L)5900MM X (W)700MM X(H) 2480MM',
  13410,
  'Busan, South Korea',
  'Port of Seattle, Seattle, Washington',
  'Maritime',
  'APL CHONGQING',
  '2025-08-03',
  'TJIFMC000023',
  'real_ocean_shipments_100.xml'
),
(
  'Lactalis Usa',
  'Lactalis Investissements',
  'France',
  'Illinois International Port District, Chicago, Illinois',
  'Belmont',
  'Wisconsin',
  '53510',
  'PACKAGES SLAC 400 BLOCKMOULD 147 - IN 3X4 BLUE COLOR 88 MAT 642X499 WITH 4 CHAMFERS - PARMA COLOR 21 MAT 642X499 WITH 4 CHAMFERS - NATURAL COLOR INCOTERM: DAP BELMONT HS: 392690 SCAC SHPT HBL 82199494',
  1188,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'SHPT82199494',
  'real_ocean_shipments_100.xml'
),
(
  'Chanvra Materials',
  'La Chanvriere',
  'France',
  'Port Of Entry-Louisville, Louisville, Kentucky',
  'Charleston',
  'South Carolina',
  '29492',
  '700 PACKAGES TRUE HEMP HS CODE 530290 ORDER 420KY2',
  14420,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'TWUD132250893600',
  'real_ocean_shipments_100.xml'
),
(
  'Marrel Corp.',
  'Societe Marrel',
  'France',
  'Detroit/Wayne County Port Authority, Detroit, Michigan',
  'Rockford',
  'Michigan',
  '49341',
  'HOOKLIFT',
  10375,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'BALG62ME25620932',
  'real_ocean_shipments_100.xml'
),
(
  'Kysela Pere Et Fils Ltd.',
  'Champagne Roland Champion',
  'France',
  'Port of Virginia, Norfolk, Virginia',
  'Winchester',
  'Virginia',
  '22602',
  'R. CHAMPION, CHAMPAGNELESPARTELAINES-',
  170,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'BALG925112251',
  'real_ocean_shipments_100.xml'
),
(
  'Kysela Pere Et Fils Ltd.',
  'Chateau De Segries',
  'France',
  'Port of Virginia, Norfolk, Virginia',
  'Winchester',
  'Virginia',
  '22602',
  'CH. SEGRIES, LIRAC BLANC, CUVEE RESERV',
  160,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'BALG925112252',
  'real_ocean_shipments_100.xml'
),
(
  'Kysela Pere Et Fils Ltd.',
  'Confrerie Des Domaines',
  'France',
  'Port of Virginia, Norfolk, Virginia',
  'Winchester',
  'Virginia',
  '22602',
  'CABRIERES, CDP BLANC, CONFIDENTIEL',
  310,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'BALG925112253',
  'real_ocean_shipments_100.xml'
),
(
  'Kysela Pere Et Fils Ltd.',
  'Domaine Tinel Blondelet',
  'France',
  'Port of Virginia, Norfolk, Virginia',
  'Winchester',
  'Virginia',
  '22602',
  'TINEL BLONDELET, POUILLY-FUME, GENE',
  680,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'BALG925112254',
  'real_ocean_shipments_100.xml'
),
(
  'Kysela Pere Et Fils Ltd.',
  'Jean Reverdy Et Fils',
  'France',
  'Port of Virginia, Norfolk, Virginia',
  'Winchester',
  'Virginia',
  '22602',
  'REVERDY(JEAN), SANCERRE BLANC-2024 1',
  8500,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'BALG925112255',
  'real_ocean_shipments_100.xml'
),
(
  'Kysela Pere Et Fils Ltd.',
  'Savdvf',
  'France',
  'Port of Virginia, Norfolk, Virginia',
  'Winchester',
  'Virginia',
  '22602',
  'CHAUME, BOURGOGNE BLANC - 2023-12 7 CHAUME, CHABLIS - 2023 - 12X750',
  6255,
  'Le Havre, France',
  'Port of Virginia, Norfolk, Virginia',
  'Maritime',
  'COSCO HOPE',
  '2025-08-03',
  'BALG925112256',
  'real_ocean_shipments_100.xml'
);